---
all:
  vars:
    ansible_connection: ssh
    ansible_ssh_common_args: "-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o ServerAliveInterval=30"
    default_user: pi
    default_password: raspberry
    deployment_user: rasputin
    deployment_password: rasputin
    local_user:     "{{ lookup('env','USER') }}"
    local_password: "{{ lookup('env','USER') }}"
    ansible_user: "{{ deployment_user }}"
    ansible_ssh_pass: "{{ deployment_password }}"
    ansible_become_password: "{{ deployment_password }}"
    country_code: US
    time_zone: America/Los_Angeles
    google_dns_servers:
      - 8.8.8.8
      - 8.8.4.4
    k3s_install_url: https://raw.githubusercontent.com/rancher/k3s/master/install.sh
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    docker_registry_fqdn: raspberry3-wifi.example.com
    dns_ip_addr: 192.168.0.152
    subnet_cidr: 192.168.0.0/24
    wifi_gateway: 192.168.0.1
    raspberries:
      - wifi_ip_address: 192.168.0.151
        wifi_host: raspberry1-wifi
        k3s_service: k3s
      - wifi_ip_address: 192.168.0.152
        wifi_host: raspberry2-wifi
        k3s_service: k3s-agent
      - wifi_ip_address: 192.168.0.153
        wifi_host: raspberry3-wifi
        k3s_service: k3s-agent
  children:
    raspberry_directs:
      hosts:
        raspberry1:
          hostname: raspberry1
          wifi_ip_address: 192.168.0.151
          wifi_host: raspberry1-wifi
        raspberry2:
          hostname: raspberry2
          wifi_ip_address: 192.168.0.152
          wifi_host: raspberry2-wifi
        raspberry3:
          hostname: raspberry1
          wifi_ip_address: 192.168.0.153
          wifi_host: raspberry3-wifi
    raspberry_wifis:
      hosts:
        raspberry1-wifi:
          hostname: raspberry1
          wifi_ip_address: 192.168.0.151
          wifi_host: raspberry1-wifi
          k3s_service: k3s
        raspberry2-wifi:
          hostname: raspberry2
          wifi_ip_address: 192.168.0.152
          wifi_host: raspberry2-wifi
          k3s_service: k3s-agent
        raspberry3-wifi:
          hostname: raspberry3
          wifi_ip_address: 192.168.0.153
          wifi_host: raspberry3-wifi
          k3s_service: k3s-agent
    k3s_master:
      hosts:
        raspberry1-wifi:
          open_ports:
          fqdn: raspberry1-wifi.example.com
    k3s_nodes:
      vars:
        k3s_master_fqdn: raspberry1-wifi.example.com
      hosts:
        raspberry2-wifi:
          k3s_node_name: raspberry2
          fqdn: raspberry2-wifi.example.com
        raspberry3-wifi:
          k3s_node_name: raspberry3
          fqdn: raspberry3-wifi.example.com
    docker_registry_host:
      hosts:
        raspberry3-wifi:
          fqdn: raspberry3-wifi.example.com
    bind_host:
      hosts:
        raspberry2-wifi:
          wifi_ip_address: 192.168.0.152
    ca_host:
      hosts:
        raspberry3-wifi:

