---
# tasks file for etc_hosts
- name: change raspberrypi name in /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    regex: '^127.0.1.1\s+raspberrypi$'
    line: "127.0.1.1      {{ hostname }}"
    state: present
- name: add all raspberry wifi ip to /etc/hosts
  become: yes
  blockinfile:
    path: /etc/hosts
    block: |
      {% for raspberry in raspberries %}
      {{ raspberry.wifi_ip_address }}   {{ raspberry.wifi_host }}
      {% endfor %}
    state: present
