---
# tasks file for ca
- name: copy ca directories
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0755"
    owner: root
    group: root
    force: no
  loop:
    - src: ca/root/
      dest: "{{ ca_root_dir }}"
    - src: ca/intermediate/
      dest: "{{ ca_intermediate_dir }}"

- name: make private the private directories
  become: yes
  file:
    path: "{{ dir }}/private"
    mode: "0700"
  loop:
    - "{{ ca_root_dir }}"
    - "{{ ca_intermediate_dir }}"
  loop_control:
    loop_var: dir

- name: template root openssl.cnf
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - src: templates/ca/root/openssl.cnf
      dest: "{{ ca_root_dir }}"
    - src: templates/ca/intermediate/openssl.cnf
      dest: "{{ ca_intermediate_dir }}"
    - src: templates/Makefile
      dest: "{{ ca_dir }}"

- name: ca_pass.txt
  become: yes
  lineinfile:
    path: "{{ ca_pass_file }}"
    create: yes
    regex: '^$'
    line: "{{ ca_passphrase }}"
    mode: '0400'

# Makefile for generating certs
- name: make
  become: yes
  make:
    chdir: "{{ ca_dir }}"
    target: "all"

- name: fetch certs
  become: yes
  fetch:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/fetch/certs/"
    flat: yes
  loop:
    - "{{ ca_root_dir}}/certs/ca.cert.pem"
    - "{{ ca_intermediate_dir }}/certs/intermediate.cert.pem"
    - "{{ ca_intermediate_dir }}/private/{{ common_name }}.key.pem"
    - "{{ ca_intermediate_dir }}/certs/{{ common_name }}-chain.crt"
