---
# tasks file for kubernetes
- name: install python kubernetes module
  become: yes
  pip:
    name: "{{ module_name }}"
    state: present
  loop:
    - kubernetes
    - openshift
  loop_control:
    loop_var: module_name
- name: testing directory
  file:
    path: ./testing
    state: directory
    mode: '0755'
- name: testing directory
  file:
    path: ./dev
    state: directory
    mode: '0755'

- name: docker pull kuard
  docker_image:
    name: "{{ kuard_image }}"
    source: pull
- name: kuard templates
  template:
    src: templates/{{ item }}
    dest: ./dev/{{ item }}
    mode: 0644
  loop:
    - "{{ kuard_pod_file }}"
    - "{{ kuard_rs_file }}"
    - kuard-service.yaml
- name: Create dev namespace
  become: yes
  k8s:
    name: dev
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "{{ kubeconfig }}"
- name: kubectl apply --filename={{ item.file }}
  become: yes
  k8s:
    namespace: dev
    kind: "{{ item.kind }}"
    name: kuard
    src: ./dev/{{ item.file }}
    state: present
    kubeconfig: "{{ kubeconfig }}"
  loop:
    - kind: ReplicaSet
      file: "{{ kuard_rs_file }}"
    - kind: Service
      file: kuard-service.yaml
