---
apiVersion: v1
kind: Pod
metadata:
  name: kuard
  namespace: dev
spec:
  containers:
    - name: kuard
      image: {{ docker_registry_fqdn }}/kuard-arm:1
      #image: gcr.io/kuar-demo/kuard-arm:1
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP

