---
apiVersion: v1
kind: Pod
metadata:
  name: kuard
  namespace: dev
spec:
  containers:
    - name: kuard
      image: {{ kuard_image }}
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP

